[directory]
dir = "E:/prayer-partners/directory.xlsx"

[email]
username = "pessognellisa20@gmail.com"
password = "jlnd hxuq wvkz wxpl"

[authorized-user]
username = "pessognellisa20@gmail.com"

[paths]
dist = "E:/prayer-partners/dist"
